version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    image: ai-interview-api:dev
    container_name: ai-interview-api
    command: bundle exec rails s -b 0.0.0.0 -p 3001
    ports:
      - "3001:3001"
    volumes:
      - ./api:/ai-interview
    env_file:
      - ./api/.env
    environment:
      - RAILS_ENV=development
      # Use host.docker.internal for container-to-host bridge routing if localhost is used
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgrespw123@host.docker.internal:5432/rakamin_development}
      - REDIS_URI=${REDIS_URI:-redis://:redispw123@host.docker.internal:6379/0}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    image: ai-interview-api:dev
    container_name: ai-interview-worker
    command: bundle exec sidekiq -r ./config/environment.rb -C config/sidekiq.yml
    volumes:
      - ./api:/ai-interview
    env_file:
      - ./api/.env
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgrespw123@host.docker.internal:5432/rakamin_development}
      - REDIS_URI=${REDIS_URI:-redis://:redispw123@host.docker.internal:6379/0}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - api
